version: "3.7"
services:
  # Laravel Service
  api:
    container_name: shift_test_api
    restart: always
    tty: true
    working_dir: /var/www/test/backend
    build:
      context: .
      dockerfile: DockerfileAPI
    environment:
      XDEBUG_CONFIG: "idekey=IDE_DEBUG"
      PHP_IDE_CONFIG: "serverName=shift_test_api"
    depends_on:
      - database
    links:
      - database
    networks:
      - shift_test_network

  # React Service
  ui:
    container_name: shift_test_ui
    restart: always
    working_dir: /var/www/test/frontend
    build:
      context: .
      dockerfile: DockerfileUI
    environment:
      NODE_ENV: development
    networks:
      - shift_test_network

  #DB Service
  database:
    image: mysql:5.7
    container_name: shift_test_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    working_dir: /etc/mysql
    tty: true
    environment:
      MYSQL_DATABASE: shift
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret 
      MYSQL_PASSWORD: 
    ports:
      - 3333:3306
    networks:
      - shift_test_network

  #Nginx Service
  server:
    image: nginx:alpine
    container_name: shift_test_server
    restart: always
    tty: true
    ports:
      - 8100:8080
      - 80:3001
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/test:rw
    working_dir: /var/www/test
    depends_on:
      - api
      - ui
    networks:
      - shift_test_network

#Docker Networks
networks:
  shift_test_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
